CREATE DATABASE skylink;

CREATE TABLE usuario(
    id VARCHAR(20) PRIMARY KEY,
    rol INT NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    apellidos VARCHAR(255) NOT NULL,
    correo VARCHAR(255) UNIQUE NOT NULL,
    clave VARCHAR(255) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    fecha DATE NOT NULL,
    pais VARCHAR(100) NOT NULL,
    millas INT NOT NULL DEFAULT 0
);

CREATE TABLE AEROPUERTO (
    Id_Aeropuerto INT PRIMARY KEY,
    Pais VARCHAR(100),
    Nombre VARCHAR(100),
    Ciudad VARCHAR(100));

INSERT INTO AEROPUERTO (Id_Aeropuerto, Pais, Nombre, Ciudad) VALUES
(1, 'Estados Unidos', 'John F. Kennedy International Airport', 'New York'),
(2, 'Reino Unido', 'Heathrow Airport', 'London'),
(3, 'Francia', 'Charles de Gaulle Airport', 'Paris'),
(4, 'Alemania', 'Frankfurt Airport', 'Frankfurt'),
(5, 'Japón', 'Tokyo Haneda Airport', 'Tokyo'),
(6, 'China', 'Beijing Capital International Airport', 'Beijing'),
(7, 'Emiratos Árabes Unidos', 'Dubai International Airport', 'Dubai'),
(8, 'Singapur', 'Changi Airport', 'Singapore'),
(9, 'Países Bajos', 'Amsterdam Airport Schiphol', 'Amsterdam'),
(10, 'Australia', 'Sydney Airport', 'Sydney'),
(11, 'Corea del Sur', 'Incheon International Airport', 'Seoul'),
(12, 'Canadá', 'Toronto Pearson International Airport', 'Toronto'),
(13, 'Turquía', 'Istanbul Airport', 'Istanbul'),
(14, 'Rusia', 'Sheremetyevo International Airport', 'Moscow'),
(15, 'España', 'Adolfo Suárez Madrid–Barajas Airport', 'Madrid'),
(16, 'Italia', 'Leonardo da Vinci–Fiumicino Airport', 'Rome'),
(17, 'India', 'Indira Gandhi International Airport', 'Delhi'),
(18, 'Tailandia', 'Suvarnabhumi Airport', 'Bangkok'),
(19, 'Malasia', 'Kuala Lumpur International Airport', 'Kuala Lumpur'),
(20, 'México', 'Mexico City International Airport', 'Mexico City'),
(21, 'Brasil', 'São Paulo/Guarulhos–Governador André Franco Montoro International Airport', 'São Paulo'),
(22, 'Suiza', 'Zurich Airport', 'Zurich'),
(23, 'Suecia', 'Stockholm Arlanda Airport', 'Stockholm'),
(24, 'Noruega', 'Oslo Airport, Gardermoen', 'Oslo'),
(25, 'Dinamarca', 'Copenhagen Airport', 'Copenhagen'),
(26, 'Argentina', 'Ministro Pistarini International Airport', 'Buenos Aires'),
(27, 'Chile', 'Arturo Merino Benítez International Airport', 'Santiago'),
(28, 'Colombia', 'El Dorado International Airport', 'Bogotá'),
(29, 'Perú', 'Jorge Chávez International Airport', 'Lima'),
(30, 'Egipto', 'Cairo International Airport', 'Cairo'),
(31, 'Grecia', 'Athens International Airport', 'Athens'),
(32, 'Portugal', 'Lisbon Portela Airport', 'Lisbon'),
(33, 'Irlanda', 'Dublin Airport', 'Dublin'),
(34, 'Bélgica', 'Brussels Airport', 'Brussels'),
(35, 'Austria', 'Vienna International Airport', 'Vienna'),
(36, 'Finlandia', 'Helsinki-Vantaa Airport', 'Helsinki'),
(37, 'Polonia', 'Warsaw Chopin Airport', 'Warsaw'),
(38, 'República Checa', 'Václav Havel Airport Prague', 'Prague'),
(39, 'Hungría', 'Budapest Ferenc Liszt International Airport', 'Budapest'),
(40, 'Ucrania', 'Boryspil International Airport', 'Kyiv'),
(41, 'Israel', 'Ben Gurion Airport', 'Tel Aviv'),
(42, 'Arabia Saudita', 'King Abdulaziz International Airport', 'Jeddah'),
(43, 'Qatar', 'Hamad International Airport', 'Doha'),
(44, 'Kuwait', 'Kuwait International Airport', 'Kuwait City'),
(45, 'Nueva Zelanda', 'Auckland Airport', 'Auckland'),
(46, 'Irán', 'Tehran Imam Khomeini International Airport', 'Tehran'),
(47, 'Vietnam', 'Tan Son Nhat International Airport', 'Ho Chi Minh City'),
(48, 'Filipinas', 'Ninoy Aquino International Airport', 'Manila'),
(49, 'Indonesia', 'Soekarno–Hatta International Airport', 'Jakarta'),
(50, 'Sudáfrica', 'O. R. Tambo International Airport', 'Johannesburg'),
(51, 'Nigeria', 'Murtala Muhammed International Airport', 'Lagos'),
(52, 'Kenia', 'Jomo Kenyatta International Airport', 'Nairobi'),
(53, 'Etiopía', 'Addis Ababa Bole International Airport', 'Addis Ababa'),
(54, 'Ecuador', 'Mariscal Sucre International Airport', 'Quito'),
(55, 'Venezuela', 'Simón Bolívar International Airport', 'Caracas'),
(56, 'Uruguay', 'Carrasco International Airport', 'Montevideo'),
(57, 'Paraguay', 'Silvio Pettirossi International Airport', 'Asunción'),
(58, 'Costa Rica', 'Juan Santamaría International Airport', 'San José'),
(59, 'Guatemala', 'La Aurora International Airport', 'Guatemala City'),
(60, 'Cuba', 'José Martí International Airport', 'Havana'),
(61, 'República Dominicana', 'Punta Cana International Airport', 'Punta Cana'),
(62, 'Honduras', 'Toncontín International Airport', 'Tegucigalpa'),
(63, 'El Salvador', 'Monseñor Óscar Arnulfo Romero International Airport', 'San Salvador'),
(64, 'Nicaragua', 'Augusto C. Sandino International Airport', 'Managua'),
(65, 'Panamá', 'Tocumen International Airport', 'Panama City'),
(66, 'Bolivia', 'El Alto International Airport', 'La Paz'),
(67, 'Chile', 'Comodoro Arturo Merino Benítez International Airport', 'Santiago'),
(68, 'Colombia', 'José María Córdova International Airport', 'Medellín'),
(69, 'Perú', 'Alejandro Velasco Astete International Airport', 'Cusco'),
(70, 'Argentina', 'Aeroparque Jorge Newbery', 'Buenos Aires'),
(71, 'Brasil', 'Brasília International Airport', 'Brasília'),
(72, 'México', 'Cancún International Airport', 'Cancún'),
(73, 'España', 'Barcelona–El Prat Airport', 'Barcelona'),
(74, 'Italia', 'Malpensa Airport', 'Milan'),
(75, 'Australia', 'Melbourne Airport', 'Melbourne'),
(76, 'Corea del Sur', 'Gimhae International Airport', 'Busan'),
(77, 'India', 'Chhatrapati Shivaji Maharaj International Airport', 'Mumbai'),
(78, 'Singapur', 'Seletar Airport', 'Singapore'),
(79, 'Países Bajos', 'Rotterdam The Hague Airport', 'Rotterdam'),
(80, 'Canadá', 'Vancouver International Airport', 'Vancouver'),
(81, 'Rusia', 'Domodedovo International Airport', 'Moscow'),
(82, 'Emiratos Árabes Unidos', 'Abu Dhabi International Airport', 'Abu Dhabi'),
(83, 'China', 'Shanghai Pudong International Airport', 'Shanghai'),
(84, 'Japón', 'Osaka Kansai International Airport', 'Osaka'),
(85, 'Alemania', 'Munich Airport', 'Munich'),
(86, 'Francia', 'Orly Airport', 'Paris'),
(87, 'Reino Unido', 'Manchester Airport', 'Manchester'),
(88, 'Estados Unidos', 'Los Angeles International Airport', 'Los Angeles'),
(89, 'Estados Unidos', 'Chicago O''Hare International Airport', 'Chicago'),
(90, 'Estados Unidos', 'Miami International Airport', 'Miami'),
(91, 'Estados Unidos', 'San Francisco International Airport', 'San Francisco'),
(92, 'Estados Unidos', 'Denver International Airport', 'Denver'),
(93, 'Estados Unidos', 'Dallas/Fort Worth International Airport', 'Dallas'),
(94, 'Estados Unidos', 'Seattle-Tacoma International Airport', 'Seattle'),
(95, 'Estados Unidos', 'Orlando International Airport', 'Orlando'),
(96, 'Estados Unidos', 'McCarran International Airport', 'Las Vegas'),
(97, 'Estados Unidos', 'George Bush Intercontinental Airport', 'Houston'),
(98, 'Estados Unidos', 'Phoenix Sky Harbor International Airport', 'Phoenix'),
(99, 'Estados Unidos', 'Philadelphia International Airport', 'Philadelphia'),
(100, 'Estados Unidos', 'Detroit Metropolitan Wayne County Airport', 'Detroit'),
(101, 'Estados Unidos', 'Minneapolis-Saint Paul International Airport', 'Minneapolis'),
(102, 'Estados Unidos', 'Logan International Airport', 'Boston'),
(103, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(104, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(105, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(106, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(107, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(108, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(109, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(110, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(111, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(112, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(113, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(114, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(115, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(116, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(117, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(118, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(119, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(120, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(121, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(122, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(123, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(124, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(125, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(126, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(127, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(128, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(129, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(130, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(131, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(132, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(133, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(134, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(135, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(136, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(137, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(138, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(139, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(140, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(141, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(142, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(143, 'Estados Unidos', 'Detroit Metropolitan Wayne County Airport', 'Detroit'),
(144, 'Estados Unidos', 'Minneapolis-Saint Paul International Airport', 'Minneapolis'),
(145, 'Estados Unidos', 'Logan International Airport', 'Boston'),
(146, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(147, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(148, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(149, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(150, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(151, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(152, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(153, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(154, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(155, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(156, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(157, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(158, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(159, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(160, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(161, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(162, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(163, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(164, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(165, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(166, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(167, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(168, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(169, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(170, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(171, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(172, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(173, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(174, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(175, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(176, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(177, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(178, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(179, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(180, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(181, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(182, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(183, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(184, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(185, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(186, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(187, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(188, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(189, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(190, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(191, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(192, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(193, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(194, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(195, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(196, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(197, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(198, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(199, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(200, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(201, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(202, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(203, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(204, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(205, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(206, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(207, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(208, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(209, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(210, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(211, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(212, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(213, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(214, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(215, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(216, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(217, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(218, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(219, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(220, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(221, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(222, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(223, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(224, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(225, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(226, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(227, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(228, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(229, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(230, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(231, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(232, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(233, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(234, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(235, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(236, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(237, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(238, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(239, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(240, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(241, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(242, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(243, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(244, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(245, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(246, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(247, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(248, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(249, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(250, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(251, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(252, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(253, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(254, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(255, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(256, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(257, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(258, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(259, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(260, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(261, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(262, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(263, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(264, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(265, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(266, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(267, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(268, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(269, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(270, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(271, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(272, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(273, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(274, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(275, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(276, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(277, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(278, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(279, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(280, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(281, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(282, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(283, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(284, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(285, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(286, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(287, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(288, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(289, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(290, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(291, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(292, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(293, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(294, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(295, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(296, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(297, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(298, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(299, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(300, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(301, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(302, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(303, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(304, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(305, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(306, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(307, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(308, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(309, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(310, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(311, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(312, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(313, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(314, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(315, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(316, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(317, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(318, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(319, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(320, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(321, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(322, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(323, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(324, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(325, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(326, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(327, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(328, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(329, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(330, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(331, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(332, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(333, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(334, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(335, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(336, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(337, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(338, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(339, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(340, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(341, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(342, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(343, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(344, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(345, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(346, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(347, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(348, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(349, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(350, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(351, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(352, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(353, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(354, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(355, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(356, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(357, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(358, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(359, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(360, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(361, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(362, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(363, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(364, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(365, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(366, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(367, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(368, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(369, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(370, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(371, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(372, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(373, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(374, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(375, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(376, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(377, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(378, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(379, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(380, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(381, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(382, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(383, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(384, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(385, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(386, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(387, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(388, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(389, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(390, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(391, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(392, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(393, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(394, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(395, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(396, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(397, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(398, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(399, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(400, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(401, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(402, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(403, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(404, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(405, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(406, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(407, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(408, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(409, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(410, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(411, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(412, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(413, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(414, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(415, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(416, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(417, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(418, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(419, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(420, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(421, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(422, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(423, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(424, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(425, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(426, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(427, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(428, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(429, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(430, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(431, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(432, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(433, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(434, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(435, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(436, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(437, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(438, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(439, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(440, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(441, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(442, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(443, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(444, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(445, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(446, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(447, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(448, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(449, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(450, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(451, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(452, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(453, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(454, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(455, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(456, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(457, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(458, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(459, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(460, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(461, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(462, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(463, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(464, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(465, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(466, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(467, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(468, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(469, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(470, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(471, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(472, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(473, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(474, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(475, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(476, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(477, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(478, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(479, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(480, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(481, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(482, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(483, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(484, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(485, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(486, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(487, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(488, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(489, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(490, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(491, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(492, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(493, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(494, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(495, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(496, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(497, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(498, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(499, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(500, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(501, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(502, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(503, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(504, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(505, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(506, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(507, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(508, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(509, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(510, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(511, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(512, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(513, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(514, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(515, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(516, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(517, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(518, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(519, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(520, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(521, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(522, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(523, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(524, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(525, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(526, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(527, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(528, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(529, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(530, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(531, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(532, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(533, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(534, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(535, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(536, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(537, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(538, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(539, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(540, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(541, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(542, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(543, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(544, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(545, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(546, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(547, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(548, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(549, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(550, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(551, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(552, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(553, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(554, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(555, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(556, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(557, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(558, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(559, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(560, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(561, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(562, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(563, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(564, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(565, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(566, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(567, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(568, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(569, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(570, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(571, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(572, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(573, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(574, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(575, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(576, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(577, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(578, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(579, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(580, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(581, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(582, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(583, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(584, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(585, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(586, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(587, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(588, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(589, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(590, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(591, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(592, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(593, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(594, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(595, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(596, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(597, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(598, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(599, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(600, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(601, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(602, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(603, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(604, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(605, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(606, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(607, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(608, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(609, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(610, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(611, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(612, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(613, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(614, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(615, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(616, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(617, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(618, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(619, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(620, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(621, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(622, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(623, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(624, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(625, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(626, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(627, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(628, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(629, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(630, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(631, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(632, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(633, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(634, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(635, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(636, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(637, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(638, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(639, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(640, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(641, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(642, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(643, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(644, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(645, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(646, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(647, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(648, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(649, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(650, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(651, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(652, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(653, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(654, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(655, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(656, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(657, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(658, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(659, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(660, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(661, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(662, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(663, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(664, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(665, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(666, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(667, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(668, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(669, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(670, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(671, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(672, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(673, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(674, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(675, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(676, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(677, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(678, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(679, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(680, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(681, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(682, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(683, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(684, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(685, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(686, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(687, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(688, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(689, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(690, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(691, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(692, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(693, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(694, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(695, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(696, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(697, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(698, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(699, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(700, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(701, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(702, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(703, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(704, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(705, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(706, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(707, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(708, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(709, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(710, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(711, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(712, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(713, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(714, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(715, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(716, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(717, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(718, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(719, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(720, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(721, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(722, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(723, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(724, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(725, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(726, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(727, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(728, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(729, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(730, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(731, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(732, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(733, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(734, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(735, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(736, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(737, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(738, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(739, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(740, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(741, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(742, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(743, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(744, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(745, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(746, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(747, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(748, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(749, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(750, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(751, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(752, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(753, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(754, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(755, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(756, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(757, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(758, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(759, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(760, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(761, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(762, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(763, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(764, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(765, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(766, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(767, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(768, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(769, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(770, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(771, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(772, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(773, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(774, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(775, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(776, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(777, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(778, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(779, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(780, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(781, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(782, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(783, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(784, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(785, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(786, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(787, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(788, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(789, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(790, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(791, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(792, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(793, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(794, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(795, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(796, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(797, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(798, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(799, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(800, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(801, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(802, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(803, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(804, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(805, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(806, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(807, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(808, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(809, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(810, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(811, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(812, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(813, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(814, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(815, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(816, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(817, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(818, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(819, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(820, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(821, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(822, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(823, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(824, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(825, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(826, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(827, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(828, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(829, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(830, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(831, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(832, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(833, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(834, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(835, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(836, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(837, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(838, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(839, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(840, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(841, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(842, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(843, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(844, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(845, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(846, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(847, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(848, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(849, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(850, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(851, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(852, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(853, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(854, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(855, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(856, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(857, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(858, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(859, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(860, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(861, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(862, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(863, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(864, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(865, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(866, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(867, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(868, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(869, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(870, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(871, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(872, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(873, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(874, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(875, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(876, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(877, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(878, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(879, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(880, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(881, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(882, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(883, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(884, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(885, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(886, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(887, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(888, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(889, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(890, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(891, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(892, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(893, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(894, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(895, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(896, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(897, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(898, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(899, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(900, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(901, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(902, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(903, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(904, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(905, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(906, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(907, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(908, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(909, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(910, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(911, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(912, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(913, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(914, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(915, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(916, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(917, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(918, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(919, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(920, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(921, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(922, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(923, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(924, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(925, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(926, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(927, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(928, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(929, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(930, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(931, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(932, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(933, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(934, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(935, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(936, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(937, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(938, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(939, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(940, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(941, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(942, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(943, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(944, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(945, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(946, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(947, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(948, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(949, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(950, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(951, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(952, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(953, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(954, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(955, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(956, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(957, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(958, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(959, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(960, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(961, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(962, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(963, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(964, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(965, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(966, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(967, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(968, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(969, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(970, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(971, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(972, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(973, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(974, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(975, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(976, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(977, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(978, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(979, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(980, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(981, 'Estados Unidos', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati'),
(982, 'Estados Unidos', 'Raleigh-Durham International Airport', 'Raleigh'),
(983, 'Estados Unidos', 'William P. Hobby Airport', 'Houston'),
(984, 'Estados Unidos', 'San Jose International Airport', 'San Jose'),
(985, 'Estados Unidos', 'Pittsburgh International Airport', 'Pittsburgh'),
(986, 'Estados Unidos', 'Salt Lake City International Airport', 'Salt Lake City'),
(987, 'Estados Unidos', 'San Diego International Airport', 'San Diego'),
(988, 'Estados Unidos', 'LaGuardia Airport', 'New York'),
(989, 'Estados Unidos', 'Ronald Reagan Washington National Airport', 'Washington, D.C.'),
(990, 'Estados Unidos', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta'),
(991, 'Estados Unidos', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale'),
(992, 'Estados Unidos', 'San Antonio International Airport', 'San Antonio'),
(993, 'Estados Unidos', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore'),
(994, 'Estados Unidos', 'Charlotte Douglas International Airport', 'Charlotte'),
(995, 'Estados Unidos', 'Austin-Bergstrom International Airport', 'Austin'),
(996, 'Estados Unidos', 'Nashville International Airport', 'Nashville'),
(997, 'Estados Unidos', 'Tampa International Airport', 'Tampa'),
(998, 'Estados Unidos', 'Portland International Airport', 'Portland'),
(999, 'Estados Unidos', 'Louis Armstrong New Orleans International Airport', 'New Orleans'),
(1000, 'Estados Unidos', 'Kansas City International Airport', 'Kansas City'),
(1001, 'Colombia', 'Rafael Núñez International Airport', 'Cartagena'),
(1002, 'Colombia', 'Alfonso Bonilla Aragón International Airport', 'Cali'),
(1003, 'Colombia', 'Ernesto Cortissoz International Airport', 'Barranquilla'),
(1004, 'Colombia', 'Palonegro International Airport', 'Bucaramanga'),
(1005, 'Colombia', 'Matecaña International Airport', 'Pereira'),
(1006, 'Colombia', 'Gustavo Rojas Pinilla International Airport', 'San Andrés'),
(1007, 'Colombia', 'Olaya Herrera Airport', 'Medellín'),
(1008, 'Colombia', 'Camilo Daza International Airport', 'Cúcuta'),
(1009, 'Colombia', 'Los Garzones Airport', 'Montería'),
(1010, 'Colombia', 'El Caraño Airport', 'Quibdó');

